### ISSUE TITLE
Perhaps add adblocking hosts file

### ISSUE THREAD

**Issue by Jan-PieterBaert** [tibovanheule/anti-distraction#1]
You can block most adds via the hosts file (except for ads on youtube and a few others), this makes your network usage lower than a normal adblocker.

Repo:
https://github.com/StevenBlack/hosts

**Comment by tibovanheule** [comment]
The repo was meant to be as an extension of that repo. 
If you truly want to block ads then use StevenBlack's hosts repo.
This just a collection of sites who distract me during exams, so it is just an temp host file.

But you can always add adblocking, in a new host file to this repo. many systems support multiple hosts files.
